# Generated by Django 4.2.9 on 2024-02-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_price_count_product_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='product_img',
            field=models.ManyToManyField(to='product.productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
