# Generated by Django 4.2.9 on 2024-02-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_currency_discount_alter_price_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='currency_ids',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='prices_by_currency', to='product.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='discount_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='prices_by_discount', to='product.discount'),
            preserve_default=False,
        ),
    ]
