# Generated by Django 4.2.9 on 2024-02-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_price_currency_ids_remove_price_discount_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
