# Generated by Django 4.2.9 on 2024-02-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_currency_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='count',
            field=models.PositiveIntegerField(default=-2021),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
