# Generated by Django 4.2.9 on 2024-02-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_discount_count_alter_currency_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=-2024, max_digits=10),
            preserve_default=False,
        ),
    ]
