# Generated by Django 4.2.9 on 2024-02-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_price_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='percent',
        ),
        migrations.AddField(
            model_name='discount',
            name='discount',
            field=models.PositiveIntegerField(default=-2024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
