# Generated by Django 4.2.9 on 2024-02-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_discount_percent_discount_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
