# Generated by Django 4.2.9 on 2024-02-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_discount_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Category Title'),
        ),
        migrations.AlterField(
            model_name='size',
            name='slug',
            field=models.SlugField(max_length=255, unique_for_date=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Size title'),
        ),
    ]
