# Generated by Django 4.2.9 on 2024-02-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_discount_id_alter_size_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='price',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices_by_color', to='product.color'),
        ),
        migrations.AlterField(
            model_name='price',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices_by_size', to='product.size'),
        ),
    ]
