# Generated by Django 4.2.9 on 2024-02-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_comment_reating_alter_price_color_alter_price_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
